// Extracts Roboto TTF base64 from pdfmake vfs_fonts and writes robotoBase64.ts
// Run from repo root: node scripts/extractPdfmakeFont.js
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const vfsPath = path.join(__dirname, "../node_modules/pdfmake/build/vfs_fonts.js");
const outFile = path.join(__dirname, "../src/lib/fonts/robotoBase64.ts");

const code = fs.readFileSync(vfsPath, "utf-8");

const vfsHolder = {};
const fn = new Function("exports", code + "\nexports.vfs = vfs;");
fn(vfsHolder);

const vfs = vfsHolder.vfs;
const keys = Object.keys(vfs);
console.log("All keys:", keys);

const regular = vfs["Roboto-Regular.ttf"] || null;
const bold = vfs["Roboto-Medium.ttf"] || vfs["Roboto-Bold.ttf"] || null;

if (!regular) {
  console.error("Roboto-Regular.ttf NOT found. Keys:", keys);
  process.exit(1);
}

const ts = [
  "// Auto-generated by scripts/extractPdfmakeFont.js — do not edit manually.",
  "// Roboto TTF from pdfmake/vfs_fonts (Apache 2.0). Full Unicode: Latin, Latin-Ext, Cyrillic.",
  "export const ROBOTO_REGULAR_B64: string =",
  '  "' + regular + '";',
  "export const ROBOTO_BOLD_B64: string =",
  '  "' + (bold || regular) + '";',
].join("\n");

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, ts, "utf-8");
console.log("Written:", outFile);
console.log("Regular chars:", regular.length, "| Bold chars:", (bold || regular).length);
